//A whole bunch of imports because this is painful
import * as React from 'react';
import { Text, View, StyleSheet, Button, Alert, SafeAreaView } from 'react-native';
import Constants from 'expo-constants';

//The following imports I don't know the purpose of, these were generated by expo.io
// You can import from local files
import AssetExample from './components/AssetExample';

// or any pure javascript modules available in npm
import { Card } from 'react-native-paper';


export default function App() {
  return (
    //The lines below for Button is to actually generate the button, the SafeAreaView is to make the
      //standalone button visible when testing the code on expo
    <SafeAreaView style ={styles.container}>
      <View>
        <Button 
          title = "Request Waiter"
          color="#000"
          onPress = {()=>Alert.alert('Waiter has been requested')}
        />
        
      </View>
    </SafeAreaView>
  );
}

//This portion is just to make the button itself when coded to be centered on the screen
const styles = StyleSheet.create({
  container:{
    flex:1,
    justifyContent:'center',
    marginHorizontal:16
  },
  title:{
    textAlign:'center',
    marginVertical:8
  },
  fitToText:{
    flexDirection:'row',
    justifyContent:'space-between'
  },
  separator:{
    marginVertical:8,
  },
})
